export interface Post {
  title: string;
  category: string;
  subcategory?: string;
  /** Canonical URL segment; set when category display name is not trivially slugified */
  categorySlug?: string;
  subcategorySlug?: string;
  date?: string;
  slug: string;
  excerpt: string;
  content?: string;
}

export interface PostMetadata {
  title: string;
  slug: string;
  excerpt: string;
  category?: string;
  subcategory?: string;
  categorySlug?: string;
  subcategorySlug?: string;
  /** True when the markdown file has more than the configured minimum line count (see post-completion.json). */
  written?: boolean;
}

export interface CategoryTree {
  name: string;
  slug: string;
  count: number;
  subcategories: SubCategory[];
  /** All subcategories have every post written. */
  completed?: boolean;
}

export interface SubCategory {
  name: string;
  slug: string;
  count: number;
  posts?: PostMetadata[];
  /** All posts in this subcategory are written. */
  completed?: boolean;
}

/** Generated by scripts/generate-post-completion.mjs; loaded at /post-completion.json */
export interface PostCompletionFile {
  minLines: number;
  generatedAt?: string;
  posts: Record<string, { lineCount: number; written: boolean }>;
}

export interface PredefinedSubcategory {
  name: string;
  slug: string;
  posts: PostMetadata[];
}

export interface PredefinedCategory {
  name: string;
  slug: string;
  subcategories: PredefinedSubcategory[];
}

export interface PredefinedCategories {
  [categorySlug: string]: PredefinedCategory;
} 